openapi: 3.0.0
servers:
  - description: Local Http Instance
    url: http://localhost:3000
info:
  title: NestJS API Swagger
  description: 'A simple NestJS API with Swagger documentation.'
  version: "v1"
  contact:
    name: Lucas Cosmo Rocha
    url: https://github.com/lucasrochagit
    email: lucascosmorocha@gmail.com
  termsOfService: 'https://github.com/lucasrochagit/swagger-annotation-vs-yaml/blob/main/LICENSE'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags: []
paths:
  "/users":
    post:
      operationId: UserController_createUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserDTO"
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserDTO"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      tags:
      - users
    get:
      operationId: UserController_getAllUsers
      parameters: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/UserDTO"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      tags:
      - users
  "/users/{user_id}":
    get:
      operationId: UserController_getUserById
      parameters:
      - name: user_id
        required: true
        in: path
        schema:
          type: number
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/UserDTO"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      tags:
      - users
    put:
      operationId: UserController_updateUser
      parameters:
      - name: user_id
        required: true
        in: path
        schema:
          type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserDTO"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserDTO"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      tags:
      - users
    delete:
      operationId: UserController_deleteUser
      parameters:
      - name: user_id
        required: true
        in: path
        schema:
          type: number
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      tags:
      - users

components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: number
          readOnly: true
          description: id of user
          example: 1
        name:
          type: string
          description: name of user
          example: Mock
        age:
          type: number
          description: age of user
          example: 23
        job:
          type: string
          description: job of user
          example: developer
      required:
      - name
      - age
      - job